print('Helo Issufi')
print('Helo Brasil')
print('Helo World')
print('Helo Rio')
print('Helo Niteroi')
print('Good By')
print('my repository')
print('Badji')
print('issufibadji@gmail.com')
print('Helo Issufi')
print('python')
print('java')
print('c')
print('js')
print('c++')